### ISSUE TITLE
Add dates and optional authors to blog post pages

### ISSUE THREAD

**Issue by rvagg** [nodejs/new.nodejs.org#111]
Dates are missing, I don't think this is intentional, they are on the index, not sure where they should go though.

It's also be good to be able to read an author from the metadata and put that somewhere if there is one, then we could have posts by named people in the foundation and the broader community, not just faceless text. This'd have to be an optional field I suppose.

**Comment by fhemberger** [comment]
It's all there, we're just not showing it yet …
