### ISSUE TITLE
Website URL in node v4 release post

### ISSUE THREAD

**Issue by phillipj** [nodejs/new.nodejs.org#114]
Is v4's website URL in the release blog post supposed to be https://nodejs.org/docs/v4.0.0/? That URL only serves a directory index ATM.

For previous releases that URL was a complete copy of the actual website targeted that specific release, e.g. https://nodejs.org/docs/v0.12.7/

**Comment by fhemberger** [comment]
No, https://nodejs.org/docs/v4.0.0/api/ is the correct link. And we won't create full copies any longer.

**Comment by phillipj** [comment]
Hm, that would result in two links (website and documentation) having the same URL which seems kinda strange.

![image](https://cloud.githubusercontent.com/assets/1231635/9755539/18a4cc6a-56d3-11e5-8013-3db4fd27ca67.png)

What about (1) using `Website: https://nodejs.org` or (2) remove the website link entirely?

**Comment by fhemberger** [comment]
+1 for  removing the website link entirely.

@rvagg What are the future plans for the API docs? IIRC the docs team should remove the website "frame" from the API docs of previous releases, so we can drop the old website snapshots and just keep the API docs, right?

**Comment by rvagg** [comment]
That's a question for the @nodejs/documentation team as to what they intend to ship but I'd go with removing the website link, that's legacy and we're only shipping API docs for now.
