### ISSUE TITLE
Blog only shows the 4.0.0 release on new.nodejs.org

### ISSUE THREAD

**Issue by evanlucas** [nodejs/new.nodejs.org#117]
https://new.nodejs.org/en/blog/ shows the new release while https://nodejs.org/en/blog/ does not show it.

**Comment by fhemberger** [comment]
LGTM on both, maybe a caching issue on your side?

**Comment by rvagg** [comment]
likely the forced 4h cache timeout we're pushing with cloudflare on html assets, something we need to tune, perhaps by sending better headers from the server

**Comment by rvagg** [comment]
^ to clarify, the 4h is to both edge caches and the server but whenever there's a new website deploy the edge caches get purged so it'd be the browser side that's caching and a force reload should take care of it

**Comment by evanlucas** [comment]
Ah that makes sense. I see it fine now. Thanks!
