### ISSUE TITLE
Footer link to license references joyent repo

### ISSUE THREAD

**Issue by sambthompson** [nodejs/new.nodejs.org#119]
The links in the footer on each page: [Node.js Project Licensing Information](https://raw.github.com/joyent/node/master/LICENSE) link to https://raw.github.com/joyent/node/master/LICENSE. Assume this should now be to https://raw.github.com/nodejs/node/master/LICENSE, as this includes the CN for "Node contributors".

**Comment by fhemberger** [comment]
Thanks, fixed in 06bbe072cd73d5fda1bf6bcf342a3f8b3c3d69a0
