### ISSUE TITLE
docs: Differentiate markdown styles

### ISSUE THREAD

**Issue by a0viedo** [nodejs/new.nodejs.org#121]
First of all, I want to thank for all the hard work the team has been doing. Keep up with the great stuff!

Currently, for the markdown syntax changes the font is changing but it is almost unnoticeable. Example:
![img](http://imgur.com/JQspZ9w.png)

Adding a simple background color (like GitHub does) would be super helpful.

**Comment by fhemberger** [comment]
Wow, this looks weird, what Browser/OS are you using?

**Comment by a0viedo** [comment]
@fhemberger I'm using Chrome v45.0.2454.85 under Windows 7.

**Comment by phillipj** [comment]
Although it doesnt look quite as unnoticeable for me, I agree we could make inline code blocks stand out a bit more. Some cut-n-paste from github's styling:

### BEFORE

![image](https://cloud.githubusercontent.com/assets/1231635/9814265/ecf43c02-588c-11e5-8ca3-e2ced936af04.png)

### AFTER

![image](https://cloud.githubusercontent.com/assets/1231635/9814245/ba78480e-588c-11e5-8de7-69d45f914dfd.png)

**Comment by fhemberger** [comment]
@phillipj The screenshot was part of the docs, not the main website. ;)

**Comment by phillipj** [comment]
> @phillipj The screenshot was part of the docs, not the main website. ;)

Wooopsie, my bad! But that doesnt mean we cant improve it on the main site
though 😃

**Comment by fhemberger** [comment]
I knew you were going to say that. ;) Sure thing, go ahead!

**Comment by phillipj** [comment]
@fhemberger I could fix this in the docs, but I dont know where the source of those are located?

**Comment by fhemberger** [comment]
Should be in https://github.com/nodejs/docs I guess. I lost a bit track of what's "the old stuff" vs. "the new stuff". :smile:

**Comment by phillipj** [comment]
That repo is more or less empty.. Maybe someone in @nodejs/documentation has some advice about the location of https://nodejs.org/api/ source files?

**Comment by phillipj** [comment]
No luck on that team either :disappointed: Falling back to @rvagg then, which project is deployed to https://nodejs.org/api/?

**Comment by phillipj** [comment]
PR fixing this just landed https://github.com/nodejs/node/pull/3573, thanks for raising this issue :+1:

**Comment by a0viedo** [comment]
@phillipj thank you!
