### ISSUE TITLE
interactive.nodejs.org

### ISSUE THREAD

**Issue by mikeal** [nodejs/new.nodejs.org#122]
Can we setup an HTTP forward from `interactive.nodejs.org` to http://events.linuxfoundation.org/events/node-interactive

If it's too difficult to do a forward for a new subdomain we could alternatively do nodejs.org/interactive

**Comment by rvagg** [comment]
added @ https://github.com/nodejs/build/commit/6c52e9fdc804549a12bed59bcc2e964e1a6b6016
