### ISSUE TITLE
contributing to localization in locale directory

### ISSUE THREAD

**Issue by JungMinu** [nodejs/new.nodejs.org#123]
I would like to contribute to localization in `/locale/ko`
Can I ask you please explain how to contribute to `/locale/{}` for localization?
Is there any guidelines related with this issue?
Thanks in advance!

**Comment by fhemberger** [comment]
We're working on that, once everything has settled a bit.

There is also a Korean community around iojs: https://github.com/nodejs/iojs-ko, which has been taken care of by the @nodejs/iojs-ko team. I think it's a good idea to coordinate the translation efforts with them.

**Comment by JungMinu** [comment]
@fhemberger Thanks!

**Comment by mikeal** [comment]
You can translate any markdown file in the english locale to the same file on the other locale and send a pull request for it. We haven't written the docs yet though, we should open an issue for that :)
