### ISSUE TITLE
dist-files redirected to blog (was: CDN misconfigured breaking npm < 2.13.2 and < 3.1.3)

### ISSUE THREAD

**Issue by garthk** [nodejs/new.nodejs.org#124]
`http://nodejs.org/dist` is redirecting to the Node blog, breaking native module installation on fresh instances with `npm` versions prior to `2.13.2` and `3.1.3`, both of which bundle `node-gyp` version `2.0.2` which switches to `https://nodejs.org/dist` as the base URL.

Note the `Location:` header below:

```
$ curl -D - -OL http://nodejs.org/dist/v0.10.32/node-v0.10.32.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0HTTP/1.1 301 Moved Permanently
Date: Thu, 10 Sep 2015 05:47:07 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: __cfduid=df56fbaba4359107e377b536a4d7f50a81441864026; expires=Fri, 09-Sep-16 05:47:06 GMT; path=/; domain=.nodejs.org; HttpOnly
Location: https://nodejs.org/en/blog/
Server: cloudflare-nginx
CF-RAY: 2238d6170bf50b14-SYD
...
```

More detail in [this gist](https://gist.github.com/garthk/510e93affdd213768c93).

**Comment by JarnoVgr** [comment]
This also breaks hits/links from Google searches, which still use HTTP in most cases.

**Comment by fhemberger** [comment]
Related:
- https://github.com/nodejs/nodejs.org/issues/173
- https://github.com/nodejs/nodejs.org/issues/175
- https://github.com/nodejs/nodejs.org/issues/69 (A bit older, but still valid)

**Comment by kiuma** [comment]
same bug with nvm. 
I solved it changing in nvm.sh 
from http://nodejs.org/dist to https://nodejs.org/dist

then I updated the env 
export NVM_NODEJS_ORG_MIRROR="https://nodejs.org/dist"

**Comment by sjanecki** [comment]
please return to previous CDN configuration
all of my builds are failing because of this.
please help

**Comment by pnedelko** [comment]
+1, my builds are failing

**Comment by Fishrock123** [comment]
cc @rvagg / @orangemocha

**Comment by drobiazko** [comment]
Some of our dependencies is using node-gyp which downloads node.js. All builds are failing with such an error:

```
node-gyp rebuild

gyp http GET http://nodejs.org/dist/v0.10.21/node-v0.10.21.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.21/node-v0.10.21.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: incorrect header check
gyp ERR! stack     at Zlib._binding.onerror (zlib.js:295:17)
gyp ERR! System Linux 3.13.0-55-generic
gyp ERR! command "node" "/tmp/node-npm-BWnW/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
```

**Comment by alexyork** [comment]
+1 We can't deploy to production (Amazon Elastic Beanstalk)! How do we fix this...?

**Comment by amitevski** [comment]
+1
actually the response code is wrong. its a 301 to homepage.

**Comment by fhemberger** [comment]
Yes, we know and we're already working on a fix.

**Comment by rvagg** [comment]
should be fixed now, cached redirects may still get in the way however

**Comment by godric7** [comment]
Hi.

`http` links are broken, but `https` works fine though.
I managed to get around the issue, using the `npm_config_disturl` environment variable (lowercase)

`export npm_config_disturl=https://nodejs.org/dis` fixed building with node-gyp

Apparently you can also set this value in ~/.npmrc but I haven't tested it.
Hope it helps.

**Comment by alexyork** [comment]
This is fixed for me now. The redirect is gone. My browser cached the redirect, as you said, but it works now from the command line when we do npm install. Thanks so much for the quick fix :-)

**Comment by sjanecki** [comment]
DIST files are fixed. confirmed but:

http links to repo now are broken:
http://registry.npmjs.org/node-uuid/-/node-uuid-1.4.1.tgz
vs
https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.1.tgz

**Comment by rvagg** [comment]
@tereska this is an npm thing if there's a problem, but I can't see one, they both work for me

**Comment by sjanecki** [comment]
ok now they are working for me also. thanks

**Comment by fhemberger** [comment]
@godric7 Unfortunately, there doesn't seem to be a corresponding config value in npm@2 (tried `npm config edit`)

**Comment by sjanecki** [comment]
thanks for the fix!

**Comment by abhisheksoni** [comment]
I think there is still some issue with this.  When i try to download this url:
http://nodejs.org/dist/v0.12.7/node-v0.12.7-linux-x86.tar.gz it redirects me to blog

and when i try to download http://nodejs.org/dist/v0.12.7/node-v0.12.7-linux-x64.tar.gz, it is super slow any alternative mirrors i can use

**Comment by fhemberger** [comment]
Can't reproduce the redirect. Maybe it's still cached on your side? /cc @nodejs/build

**Comment by rvagg** [comment]
you may have a cached version of the redirect still? re slowness, we're using CloudFlare now so it _should_ be a lot faster than it ever was, what country are you in? Also, try `https` instead of `http` for the download, not that it should make a huge difference, however.
