### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by mikeal** [nodejs/new.nodejs.org#18]
Can we put together a list of tasks to accomplish in order to get an MVP live for the converged project.

It's very difficult to discern what needs to get done or how to get involved based on the current issues/readme. Perhaps this information is embedded somewhere in prior repos but even I can't seem to figure it out.

**Comment by Fishrock123** [comment]
Are we talking for the website or in general?

**Comment by mikeal** [comment]
Just the website.

**Comment by Fishrock123** [comment]
Absolute minimum is what's on nodejs.org moved over to our i18n build system, afaik. I'll try to put more of my own time here after I deal with `_unrefActive()`.

**Comment by fhemberger** [comment]
I think we should take the time and look at the content and overall structure as well, before we just pull everything over. There are some quirks on the current nodejs website and I think we could get rid of some of the content (or at least restructure it). That would make it easier for the translators as well.

**Comment by mikeal** [comment]
Do we want to engage the Linux Foundation to provide any design resources?

**Comment by Fishrock123** [comment]
> Do we want to engage the Linux Foundation to provide any design resources?

it was suggested by someone else, and I would prefer to ask the community for design ideas before doing anything major.

**Comment by mikeal** [comment]
@Fishrock123 We've already asked for that and even promoted it and didn't get anything usable yet.

I'd like to inject a little bit of urgency in to this. My impression right now is that things are stalled either because we feel blocked on something we can't identify or because there isn't a good starting point for people to pick up at go. 

I'm willing to block out some time to migrate the old build system over the current design and to get a new design from the LF that incorporates the new structure (although I'm probably not the best person to implement the design), documents and messaging we want to highlight. Last time the website took off after I threw up some code (quite terrible code) that was an obvious starting point for others to improve.

**Comment by fhemberger** [comment]
@mikeal I have some feedback/request about the build system, I'll write a ticket for it later. I'll also put some time into content structure and can help with the implementation of the design as well (as soon as it is available).

I think what's blocking (at least me) at the moment is that it's not yet clear, when we'll have the first "real" merged version of node/io.js and how the convergence is coming along in this part of the project. So is the core team waiting for the website to be finished or is it the other way round? Do we need a go from the foundation first or what exactly is it we are waiting for.

**Comment by mikeal** [comment]
> when we'll have the first "real" merged version of node/io.js and how the convergence is coming along in this part of the project

I don't think we need to block on this. If we have a website ready and we don't have converged releases we'll just put up both io.js and node.js releases.

**Comment by Fishrock123** [comment]
> My impression right now is that things are stalled either because we feel blocked on something we can't identify or because there isn't a good starting point for people to pick up at go.

I actually think it's just blocked on people's time.

**Comment by mikeal** [comment]
> I actually think it's just blocked on people's time.

This might be a good reason to just have the LF whip something up to move forward on. Once something is up people can still contribute to it via PRs.

**Comment by Fishrock123** [comment]
No like, I mean time to do the dirty code/build work, the design doesn't even have to change.

**Comment by mikeal** [comment]
ok, i'm gonna start dumping some code in here. it'll be the old build system with a bunch of new code for the proposed taxonomy and some stub content.

to reduce bike shedding i'm going to propose that i just commit this to master and that anyone else who wants to jump in does the same until it starts to solidify. everyone should continue to tweak the copy and style at will for a bit while we work stuff out, if you're wondering about a change then send it as a PR.

thoughts?

**Comment by Fishrock123** [comment]
> ok, i'm gonna start dumping some code in here. it'll be the old build system with a bunch of new code for the proposed taxonomy and some stub content.

Which old build system? I was hoping to dump the one from io.js here (since that's the best start) but It's gotten pushed back.

> to reduce bike shedding i'm going to propose that i just commit this to master and that anyone else who wants to jump in does the same until it starts to solidify. everyone should continue to tweak the copy and style at will for a bit while we work stuff out, if you're wondering about a change then send it as a PR.

I'd say have at it basically until it's live-on-commit like iojs.org.

**Comment by mikeal** [comment]
> Which old build system? I was hoping to dump the one from io.js here (since that's the best start) but It's gotten pushed back.

Correct, the gulp build system iojs.org uses, *not* the makefile nodejs.org is using.
