### ISSUE TITLE
Markdown content gets escaped twice

### ISSUE THREAD

**Issue by diagramatics** [nodejs/new.nodejs.org#28]
Found this when working on #27. If you try with that content on [line 18](https://github.com/nodejs/new.nodejs.org/pull/27/files#diff-823aaeb0aa1e6ff57bd5b4e06470af60R18) you can see the apostrophes escaped to `&apos;` by metalsmith-markdown, then `&amp;apos;` by metalsmith-prism.

Seems like the only way to make Prism not escape them is to use Prism's hooks and metalsmith-prism doesn't really have them exposed.

**Comment by phillipj** [comment]
After some digging I opened a PR in Availity/metalsmith-prism#6 to avoid highlighting all together for inline code blocks where language is not specified. Seems like that would fix the issue of double escaping in these blog posts.

**Comment by fhemberger** [comment]
Thank you!

**Comment by phillipj** [comment]
Cant find any escaping issues after using the newly released metalsmith-prism :dancers: Close this @fhemberger?

**Comment by fhemberger** [comment]
Yay, great! Thanks for looking after this issue.
