### ISSUE TITLE
SSL cert issues?

### ISSUE THREAD

**Issue by fhemberger** [nodejs/new.nodejs.org#60]
I think I saw a related ticket a few days ago but couldn't find it anymore. When I try to access new.nodejs.org with wget (scanning for 404s), I get the following message:

```
Resolving new.nodejs.org (new.nodejs.org)... 104.131.173.199
Connecting to new.nodejs.org (new.nodejs.org)|104.131.173.199|:443... connected.
ERROR: cannot verify new.nodejs.org's certificate, issued by 'CN=COMODO RSA Domain Validation Secure Server CA,O=COMODO CA Limited,L=Salford,ST=Greater Manchester,C=GB':
  Unable to locally verify the issuer's authority.
To connect to new.nodejs.org insecurely, use `--no-check-certificate'.
```

Browser is working fine, reporting just in case it causes issues for other tools as well.

**Comment by rvagg** [comment]
thanks, I was just tinkering with the certs but I thought I was _improving_ the chain so ...

**Comment by rvagg** [comment]
got it, I added the wrong trust cert to the chain, fixed now
