### ISSUE TITLE
New site is live with 0.12.7 everywhere, except link to changelog

### ISSUE THREAD

**Issue by sambthompson** [nodejs/new.nodejs.org#84]
Probably a known issue, but [Home page](https://nodejs.org/) lists v0.12.7 as current, but [link to changelog](https://github.com/nodejs/node/blob/master/CHANGELOG.md) on this repo is to current v3.3.0.

Looks good though.

**Comment by fhemberger** [comment]
Yes, because v0.12.7 is the latest release of node, v3.3.0 is the latest version of iojs, but the repo is already the converged project. This will be fixed with v4.0.0, which will be out either at the end of this week or next week.

**Comment by sambthompson** [comment]
So, shouldn't the Changelog link to https://github.com/nodejs/node-v0.x-archive/blob/master/ChangeLog until then?

**Comment by fhemberger** [comment]
You're right about that, changed it in 2d5bf4b823fec1170d7a20757147625055def63e.
I leave this issue open as a reminder to change it back again.

**Comment by sambthompson** [comment]
Nice one, cheers. Think it really helps as Changelog is a vital link for a site built around a software product...

**Comment by fhemberger** [comment]
Will be fixed in f0f2e4dc798dff0407ec6100107981c3383a624a, as soon as v4.0.0 goes live.
