### ISSUE TITLE
http://www.nodejs.org/ redirect loop

### ISSUE THREAD

**Issue by No9** [nodejs/new.nodejs.org#85]
http://www.nodejs.org/ loops probably the https and removal of www interfering with each other?

**Comment by rvagg** [comment]
yep, probably a combination of http -> https and www -> blank

if someone has time then could they propose a change @ https://github.com/nodejs/build/blob/master/setup/www/resources/config/nodejs.org I have to be offline for a few hours

**Comment by No9** [comment]
Suggesting this
Not tested tho!! YMMV
https://github.com/nodejs/build/compare/master...No9:patch-1

**Comment by rvagg** [comment]
fixed https://github.com/nodejs/build/pull/181
