### ISSUE TITLE
Banner & Announcements

### ISSUE THREAD

**Issue by mikeal** [nodejs/new.nodejs.org#90]
Heya,

We needed to get up a press release today and a banner for the conference so I pushed them this morning, I was going to post it as a PR and then merge it so that we had a place to talk about it after but I forgot so I'm posing this issue now :)

The banner is placed where the "Node on the Road" banner was on the old site. It's a little large but looks pretty nice, but I'm open to reducing its size if we find a better background image (this one didn't look good when I reduced the height).

Additionally, the foundation is going to be putting out press releases fairly often. I created a new "announcement" section on the blog and a filtered feed for the Foundation section. This is pretty similar to other foundation sites.

Also, announcements went out today about the board director elections and the new foundation lead event Node.js Interactive, is live.

**Comment by fhemberger** [comment]
@mikeal Next time, please look at the image sizes as well, this thing was *huge*. I optimized the PNG in Photoshop and squeezed out the last bits with ImageOptim (going down from whopping 1.2 MB to 94 KB). (Also please mind the .editorconfig *g*)

**Comment by mikeal** [comment]
> (Also please mind the .editorconfig g)

Did I modify the editorconfig?

Sorry about the image, I was on incredibly slow internet and it was all loading quite fast so I didn't worry. Of course, now I'm realizing that because I was loading it from the remote site it was already in my browser cache :/

**Comment by fhemberger** [comment]
> Did I modify the editorconfig?

No, your editor just seems to ignore the indentation settings. ;)

**Comment by mikeal** [comment]
> No, your editor just seems to ignore the indentation settings. ;)

:( I'll figure out what is going on with Atom then.
