### ISSUE TITLE
Is 1.2 MiB png photo really needed on the title page?

### ISSUE THREAD

**Issue by ChALkeR** [nodejs/new.nodejs.org#94]
I'm speaking about http://events.linuxfoundation.org/sites/events/files/styles/1920px_maxwidth/public/banner-images/portland.png now.

I see ~15% size improvement (1232339 to 1052669 bytes) after applying lossless png compression like this:
```
pngcrush -brute -reduce -ow -q portland.png
advdef -z -4 -q portland.png
```

Converting that photo to a jpg image (with default `convert` options) reduces the size 3.5x (1232339 to 345452 bytes) with almost no visible difference (that's a photo, remember?).

**Comment by fhemberger** [comment]
Of cause, you're right. Replaced the image with an optimized JPG, size is now 94 KB.
